services:
  wireguard:
    labels:
      - traefik.enable=true
      - traefik.docker.network=homelab-network
      - traefik.http.routers.wireguard.rule=Host(`wireguard.gryta.eu`)
      - traefik.http.routers.wireguard.entrypoints=websecure
      - traefik.http.routers.wireguard.tls.certresolver=le
      - traefik.http.routers.wireguard.middlewares=authentik-forward-auth@file
      - traefik.http.services.wireguard.loadbalancer.server.port=51821
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
      - PORT=51821
      - WG_PORT=55555
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=172.20.0.254
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_MTU=1420
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1
    volumes:
      - wireguard_config:/etc/wireguard
    ports:
      - 55555:55555/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      homelab-network:
        ipv4_address: 172.20.0.200
      wireguard-network:
        ipv4_address: 172.20.3.254
volumes:
  wireguard_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/quick/apps/volumes/wireguard/config
networks:
  homelab-network:
    external: true
  wireguard-network:
    external: true
