services:
  wireguard:
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.rule=Host(`wireguard.gryta.eu`)
      - traefik.http.routers.wireguard.entrypoints=websecure
      - traefik.http.routers.wireguard.tls.certresolver=le
      - traefik.http.services.wireguard.loadbalancer.server.port=51821
      - traefik.http.routers.wireguard.middlewares=authentik-forward-auth@file
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - LANG=en
      - WG_HOST=${WG_HOST}
      - PASSWORD=${WG_PASSWORD}
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=172.20.3.x
      - WG_DEFAULT_DNS=172.20.0.254
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_MTU=1420
    volumes:
      - wireguard_config:/etc/wireguard
    ports:
      - 55555:51820/udp
    networks:
      homelab-network:
        ipv4_address: 172.20.0.200
      wireguard-network:
        ipv4_address: 172.20.3.1
volumes:
  wireguard_config:
    driver_opts:
      o: bind
      type: none
      device: /mnt/quick/apps/volumes/wireguard/config
networks:
  homelab-network:
    external: true
  wireguard-network:
    name: wireguard-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
          gateway: 172.20.3.1
