# .env
# OAUTH_CLIENT_ID=
# OAUTH_CLIENT_SECRET=

services:
  prometheus:
    labels:
      - traefik.enable=false
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      cadvisor:
        condition: service_started
      node-exporter:
        condition: service_started
    user: root
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    networks:
      homelab-network:
        ipv4_address: 172.20.0.23
      monitoring-network:
        ipv4_address: 172.22.0.2
    volumes:
      - /mnt/quick/apps/volumes/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
  grafana:
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.gryta.eu`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=le
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
    environment:
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_NAME: authentik
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authentik.gryta.eu/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authentik.gryta.eu/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://authentik.gryta.eu/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://authentik.gryta.eu/application/o/grafana/end-session/"
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'lldap_admin') && 'Admin'"
      GF_SERVER_ROOT_URL: "https://grafana.gryta.eu"
    networks:
      homelab-network:
        ipv4_address: 172.20.0.22
      monitoring-network:
        ipv4_address: 172.22.0.5
    volumes:
      - grafana_data:/var/lib/grafana
  cadvisor:
    labels:
      - traefik.enable=false
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    networks:
      monitoring-network:
        ipv4_address: 172.22.0.3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  node-exporter:
    labels:
      - traefik.enable=false
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      monitoring-network:
        ipv4_address: 172.22.0.4
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"
volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/quick/apps/volumes/prometheus/data
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/quick/apps/volumes/grafana/data
networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1
  homelab-network:
    external: true
