services:
  immich-server:
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`immich.gryta.eu`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls.certresolver=le
      - traefik.http.services.immich.loadbalancer.server.port=2283
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    networks:
      homelab-network:
        ipv4_address: 172.20.0.114
    volumes:
      - /mnt/quick/immich:/data
      - immich_upload:/data2
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false
  immich-machine-learning:
    labels:
      - traefik.enable=false
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends:
      file: hwaccel.ml.yml
      service: openvino
    volumes:
      - model_cache:/cache
    networks:
      homelab-network:
        ipv4_address: 172.20.0.115
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false
volumes:
  immich_upload:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/quick/media
  model_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/quick/apps/volumes/immich/cache
networks:
  homelab-network:
    external: true
